In [4]:
import matplotlib
import numpy as np


In [1]:
#test 
print('hello')

hello


In [5]:
x = np.array([1.0, 2.0, 3.0])
print(x)
type(x)

[1. 2. 3.]


numpy.ndarray

In [7]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([4.0, 5.0, 6.0])
x + y
x - y
x * y
x / y

array([0.25, 0.4 , 0.5 ])

In [13]:
A = np.array([[1,2],[3,4]])
print(A)
print(A.shape)
print(A.dtype)

[[1 2]
 [3 4]]
(2, 2)
int32


In [16]:
B = np.array([[3, 0], [0, 6]])
print(A + B )
print(A*B)

[[ 4  2]
 [ 3 10]]
[[ 3  0]
 [ 0 24]]


In [17]:
X = np.array([[51, 55], [14, 19], [0, 4]])
print(X)

for row in X:
    print(row)

[[51 55]
 [14 19]
 [ 0  4]]
[51 55]
[14 19]
[0 4]


In [32]:
x, y = map(int, input().split())
if x*y == 1:
    z = 1
else: z = 0 
print(z)

0
